config/routes.rb
Rails.application.routes.draw do
  filter :locale

  ActiveAdmin.routes(self)

  scope "(:locale)", locale: /#{I18n.locale}/ do
    mount News::Engine => "/"
  end

  root 'main#index'

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login' => 'user_sessions#new', as: :login

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  end

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout' => 'user_sessions#destroy', as: :logout

    resources :cards do
      get 'get_flickr_images', on: :collection
      post 'parsing_html', on: :collection
    end

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'

    get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
    put 'profile/:id' => 'profile#update', as: :profile
    post 'invite_friends' => 'profile#invite_friends', as: :invite_friends
  end
end

app/models/card.rb
require 'super_memo_service'

class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :block
  before_validation :set_review_date_as_now, on: :create
  validate :texts_are_not_equal
  validates :original_text, :translated_text, :review_date,
            presence: { message: 'Необходимо заполнить поле.' }
  validates :user_id, presence: { message: 'Ошибка ассоциации.' }
  validates :block_id,
            presence: { message: 'Выберите колоду из выпадающего списка.' }
  validates :interval, :repeat, :efactor, :quality, :attempt, presence: true

  mount_uploader :image, CardImageAmazonUploader

  scope :pending, -> { where('review_date <= ?', Time.now).order('RANDOM()') }
  scope :repeating, -> { where('quality < ?', 4).order('RANDOM()') }

  def check_translation(user_translation)
    distance = Levenshtein.distance(full_downcase(translated_text),
                                    full_downcase(user_translation))

    sm_hash = SuperMemoService.algorithm(interval, repeat, efactor, attempt, distance, 1)

    if distance <= 1
      sm_hash.merge!({ review_date: Time.now + interval.to_i.days, attempt: 1 })
      update(sm_hash)
      { state: true, distance: distance }
    else
      sm_hash.merge!({ attempt: [attempt + 1, 5].min })
      update(sm_hash)
      { state: false, distance: distance }
    end
  end

  def self.pending_cards_notification
    users = User.where.not(email: nil)
    users.each do |user|
      if user.cards.pending.any?
        CardsMailer.pending_cards_notification(user.email).deliver_now
      end
    end
  end

  def self.create_from_html(user_id, block_id, original_texts, translated_texts)
    CardsParserService.create_cards_from_html(user_id, block_id, original_texts, translated_texts)
  end

  protected

  def set_review_date_as_now
    self.review_date = Time.now
  end

  def texts_are_not_equal
    if full_downcase(original_text) == full_downcase(translated_text)
      errors.add(:original_text, 'Вводимые значения должны отличаться.')
    end
  end

  def full_downcase(str)
    str.mb_chars.downcase.to_s.squeeze(' ').lstrip
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:destroy, :edit, :update]
  respond_to :html

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    respond_with @card
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id)
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = 'Вы обратились к несуществующей записи.'
    redirect_to root_path
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:destroy, :edit, :update, :set_as_current,
                                   :reset_as_current]
  respond_to :html

  def index
    @blocks = current_user.blocks.all.order('title')
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def destroy
    @block.destroy
    respond_with @block
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
require 'nokogiri'
require 'open-uri'

class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]
  respond_to :html

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    respond_with @card
  end

  def get_flickr_images
    @flickr_images = FlickrService.search_photos(
      # A free text search. Photos who's title, description or tags contain the
      # text will be returned. You can exclude results that match a term by
      # prepending it with a - character.
      params[:search],

      # The license id for photos (for possible values see the
      # flickr.photos.licenses.getInfo method). Multiple licenses may be
      # comma-separated.
      '1, 2, 3, 4, 5, 6, 7',

      # A comma-delimited list of extra information to fetch for each returned
      # record. Currently supported fields are: description, license,
      # date_upload, date_taken, owner_name, icon_server, original_format,
      # last_update, geo, tags, machine_tags, o_dims, views, media, path_alias,
      # url_sq, url_t, url_s, url_q, url_m, url_n, url_z, url_c, url_l, url_o
      'url_sq, url_m',

      # Number of photos to return per page. If this argument is omitted,
      # it defaults to 100. The maximum allowed value is 500.
      10,

      # The page of results to return. If this argument is omitted,
      # it defaults to 1.
      1
    )
  end

  def parsing_html
    parse = CardsParserService.schedule_parsing(current_user.id,
                                                parsing_html_params)
    set_flash(parse)

    respond_to do |format|
      format.js
    end
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id,
                                 :remote_image_url)
  end

  def parsing_html_params
    params.require(:parsing_html).permit(:block_id, :url, :origin_selector,
                                         :translated_selector)
  end

  def set_flash(parse)
    if parse
      flash.now[:notice] = \
        "Задача на парсинг сайта успешно поставлена в очередь."
      flash.now[:alert] = nil
    else
      flash.now[:alert] = "Проверьте правильность введенных данных."
      flash.now[:notice] = nil
    end
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::BaseController
  respond_to :html, :js

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path,
                  notice: 'Профиль пользователя успешно обновлен.'
    else
      respond_with current_user
    end
  end

  def invite_friends
    @incorrect_emails = FriendsService.invite(invite_friends_params[:emails])
    if @incorrect_emails.blank?
      flash.now[:notice] = 'Ваши друзья успешно приглашены на сайт.'
    else
      flash.now[:alert] = 'Проверьте формат вводимых данных: ' + @incorrect_emails + '.'
      flash.now[:notice] = nil
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :locale)
  end

  def invite_friends_params
    parameters = params.require(:invite_friends).permit(:emails)
    parameters[:emails] = parameters[:emails].gsub(' ', '').split(',')
    parameters
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController
  before_action :set_card, only: [:review_card]
  respond_to :js, :html

  def index
    if params[:card_id]
      set_card
    else
      if current_user.current_block
        @card = current_user.current_block.cards.pending.first
        @card ||= current_user.current_block.cards.repeating.first
      else
        @card = current_user.cards.pending.first
        @card ||= current_user.cards.repeating.first
      end
    end
  end

  def review_card
    check_result = @card.check_translation(trainer_params[:user_translation])

    if check_result[:state]
      if check_result[:distance] == 0
        flash[:notice] = t(:correct_translation_notice)
      else
        flash[:alert] = t 'translation_from_misprint_alert',
                          user_translation: trainer_params[:user_translation],
                          original_text: @card.original_text,
                          translated_text: @card.translated_text
      end
      redirect_to trainer_path
    else
      flash[:alert] = t(:incorrect_translation_alert)
      redirect_to trainer_path(card_id: @card.id)
    end
  end

  private

  def set_card
    @card = current_user.cards.find(params[:card_id])
  end

  def trainer_params
    params.require(:review_card).permit(:user_translation)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: 'Пользователь успешно удален.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/cards/_flickr_images.html.erb
<div class="row">
  <% flickr_images.each do |flickr_images| %>
    <div class="col-xs-3 col-md-2" id="flickr_image">
      <a href="#inline" class="thumbnail"
         onclick="$('#remote_image_url input').val('<%= flickr_images.url_m %>');">
        <%= image_tag flickr_images.url_sq %>
      </a>
    </div>
  <% end %>
</div>

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for card do |f| %>
  <% if card.image?%>
    <div class="form-group">
      <%= f.input :remove_image, as: :boolean, label: 'Удалить изображение' %>
      <div class="row">
        <div class="col-xs-6 col-md-4 card_image">
          <p class="thumbnail">
            <%= image_tag card.image_url %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :original_text,  as: :string, label: 'Оригинал',
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <div class="form-group">
    <%= f.input :translated_text,  as: :string, label: 'Перевод',
                input_html: { class: 'form-control', required: true } %>
  </div>

  <%= render 'loading_image', f: f %>

  <div class="form-group">
    <%= f.input :block_id, collection: current_user.blocks.all.order('title'),
                prompt: 'Выберите колоду', label: 'Колоды',
                input_html: { class: 'form-control', required: true } %>
  </div>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-default' %>
<% end %>

app/views/dashboard/cards/_loading_image.html.erb
<div class="form-group" xmlns="http://www.w3.org/1999/html">
  <%= label_tag 'Загрузка изображения' %>
  <div class="form-group">
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
      Компьютер
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
      flickr.com
    </label>
  </div>
</div>

<div class="form-group" id="load_local_image">
  <%= f.input :image, as: :file, label: 'Изображение на компьютере' %>
</div>

<div id="load_flickr_image">
  <div class="form-group">
    <%= label_tag 'Изображение на flickr.com' %>
    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <input type="text" class="form-control" name="flickr_search"
                 placeholder="Что ищем?">
			      <span class="input-group-btn">
			        <%= link_to 'Искать на flickr.com', get_flickr_images_cards_path,
			                    remote: true, class: 'btn btn-default',
			                    id: 'flickr_search_link' %>
			      </span>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group" id="flickr_images">
  </div>

  <div class="form-group" id="remote_image_url">
    <%= f.input :remote_image_url, as: :string,
                label: 'Адрес изображения на flickr.com',
                input_html: { class: 'form-control' },
                placeholder: 'Найдите изображение на flickr.com и выберите понравившееся.' %>
    <%= f.input :image_cache, as: :hidden %>
  </div>
</div>

app/views/dashboard/cards/edit.html.erb
<h2>Редактировать карточку</h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/get_flickr_images.js.erb
$('a#flickr_search_link').attr('href', '<%= get_flickr_images_cards_path %>');
$('#flickr_images').html('<%= escape_javascript render('flickr_images', flickr_images: @flickr_images) %>');

app/views/dashboard/cards/index.html.erb
<h2>Карточки</h2>

<div class="form-group">
  <%= link_to 'Добавить карточку', new_card_path, class: 'btn btn-default',
              role: 'button' %>
</div>

<% if @cards.any? %>
  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th>Оригинал</th>
      <th>Перевод</th>
      <th>Пересмотр</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @cards.each do |card| %>
      <tr class="table table-hover table-condensed">
        <td><%= card.original_text %></td>
        <td><%= card.translated_text %></td>
        <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
        <td><%= link_to 'Редактировать', edit_card_path(card) %></td>
        <td><%= link_to 'Удалить', card, method: :delete,
                        data: { confirm: 'Удалить запись?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/dashboard/cards/new.html.erb
<h2>Добавить карточку</h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/parsing_html.js.erb
$('#modal_notice_block_parsing_html').html('<%= escape_javascript render('shared/alert_notice') %>');

<% if @parse.nil? %>
  $('#modal_parsing_html textarea:first').focus();
  $('.modal_parsing_html_field_with_errors').attr('class', 'field_with_errors');
<% else %>
  $('#close_modal_parsing_html').focus();
  $('.modal_parsing_html_field_with_errors').attr('class', '');
<% end %>